/**
 * ============================================================================
 * ROOT LAYOUT COMPONENT
 * ============================================================================
 *
 * @file app/layout.tsx
 *
 * PURPOSE:
 * Root layout component wrapping all pages with providers and error boundary.
 *
 * FEATURES:
 * - NextAuth SessionProvider
 * - Error boundary for error handling
 * - Global CSS imports
 * - Metadata configuration
 *
 * RELATED FILES:
 * - components/Providers.tsx (SessionProvider wrapper)
 * - components/ErrorBoundary.tsx (Error boundary component)
 * - app/globals.css (Global styles)
 *
 * ============================================================================
 */

import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@/components/Providers';
import { ErrorBoundary } from '@/components/ErrorBoundary';

// ============================================================================
// SECTION: METADATA
// ============================================================================

/**
 * Page metadata for SEO and browser display.
 */
export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

// ============================================================================
// SECTION: ROOT LAYOUT
// ============================================================================

/**
 * Root layout component.
 *
 * Wraps all pages with:
 * - Error boundary (catches React errors)
 * - Providers (NextAuth session provider)
 *
 * @param children - Page content
 * @returns Root layout JSX
 */
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head />
      <body className="font-body antialiased">
        {/* ====================================================================
            ERROR BOUNDARY
            ==================================================================== */}
        <ErrorBoundary>
          {/* =================================================================
              PROVIDERS (NextAuth SessionProvider)
              ================================================================= */}
          <Providers>{children}</Providers>
        </ErrorBoundary>
      </body>
    </html>
  );
}
